# Generated by Django 5.2.16 on 2026-09-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("use_cases", "0010_ap2_metric_pilot_planning"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalusecase",
            name="ap2_planning_provenance",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="historicalusecase",
            name="metric_measurement_population",
            field=models.TextField(blank=True, verbose_name="Messpopulation / Stichprobe"),
        ),
        migrations.AddField(
            model_name="historicalusecase",
            name="pilot_abort_criteria",
            field=models.TextField(blank=True, verbose_name="Pilot-Abbruchkriterien"),
        ),
        migrations.AddField(
            model_name="historicalusecase",
            name="pilot_review_criteria",
            field=models.TextField(blank=True, verbose_name="Pilot-Reviewkriterien"),
        ),
        migrations.AddField(
            model_name="historicalusecase",
            name="pilot_scope",
            field=models.TextField(blank=True, verbose_name="Kleinster sinnvoller Pilot"),
        ),
    ]
