# Generated by Django 5.2.16 on 2026-09-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("use_cases", "0011_historicalusecase_ap2_planning_provenance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionassessment",
            name="ap2_provenance",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="historicalusecase",
            name="ap2_governance_draft",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="usecase",
            name="ap2_governance_draft",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
