# Generated by Django 5.2.17 on 2026-10-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0022_alter_solutionarchitectureassessment_assessed_by'),
        ('use_cases', '0013_alter_decisionassessment_assessed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideacandidate',
            name='discovery_process_analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_idea_candidate', to='architecture.processanalysis'),
        ),
    ]
