# Generated by Django 5.2.16 on 2026-09-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_ap2_metric_pilot_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmtaskquota",
            name="task_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("delivery_field_draft", "Delivery-Feldentwurf"),
                    ("ap2_metric_pilot_draft", "AP2 Metrik- und Pilotentwurf"),
                    ("ap2_architecture_inputs", "AP2 Architecture-Advisor-Eingaben"),
                    ("ap2_decision_governance_draft", "AP2 Entscheidungs- und Governance-Entwurf"),
                    ("origin_consistency_review", "Herkunfts-Konsistenzprüfung"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="llmtaskrun",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("delivery_field_draft", "Delivery-Feldentwurf"),
                    ("ap2_metric_pilot_draft", "AP2 Metrik- und Pilotentwurf"),
                    ("ap2_architecture_inputs", "AP2 Architecture-Advisor-Eingaben"),
                    ("ap2_decision_governance_draft", "AP2 Entscheidungs- und Governance-Entwurf"),
                    ("origin_consistency_review", "Herkunfts-Konsistenzprüfung"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
