from django.urls import path

from . import (\n    adoption_views,\n    investigation_views,\n    methodology_views,\n    solution_generation_views,\n    structured_views,\n    views,\n)
from .models import CaptureSession

app_name = "accelerator"

urlpatterns = [
    path(
        "processes/<uuid:process_pk>/investigation/authorize/",
        investigation_views.investigation_authorize,
        name="investigation_authorize",
    ),
    path(
        "processes/<uuid:process_pk>/investigation/start/",
        investigation_views.investigation_start,
        name="investigation_start",
    ),
    path(
        "investigations/<uuid:run_id>/",
        investigation_views.investigation_detail,
        name="investigation_detail",
    ),
    path(
        "investigations/<uuid:run_id>/abort/",
        investigation_views.investigation_abort,
        name="investigation_abort",
    ),
    path(
        "investigations/<uuid:run_id>/continue/",
        investigation_views.investigation_continue,
        name="investigation_continue",
    ),
    path(
        "investigations/<uuid:run_id>/materialize/",
        investigation_views.investigation_materialize,
        name="investigation_materialize",
    ),
    path(
        "investigations/<uuid:run_id>/export.md",
        investigation_views.investigation_export,
        name="investigation_export",
    ),
    path(
        "investigations/<uuid:run_id>/sources/<uuid:source_id>/",
        investigation_views.investigation_source,
        name="investigation_source",
    ),
    path(
        "investigations/<uuid:run_id>/tool-results/<uuid:result_id>/",
        investigation_views.investigation_tool_result,
        name="investigation_tool_result",
    ),
    path("my-captures/", views.capture_session_list, name="capture_list"),
    path(
        "value-stream/start/",
        views.start_capture,
        {"capture_type": CaptureSession.CaptureType.VALUE_STREAM},
        name="value_stream_start",
    ),
    path(
        "value-stream/methodology/download/",
        methodology_views.value_stream_methodology_download,
        name="value_stream_methodology_download",
    ),
    path(
        "use-case/start/",
        views.start_capture,
        {"capture_type": CaptureSession.CaptureType.USE_CASE},
        name="use_case_start",
    ),
    path(
        "<uuid:session_id>/step/<int:step>/",
        views.capture_step,
        name="capture_step",
    ),
    path(
        "<uuid:session_id>/review/",
        views.capture_review,
        name="capture_review",
    ),
    path(
        "<uuid:session_id>/analyze/",
        views.capture_analyze,
        name="capture_analyze",
    ),
    path(
        "analyses/<uuid:analysis_id>/",
        views.analysis_detail,
        name="analysis_detail",
    ),
    path(
        "analyses/<uuid:analysis_id>/candidates/<uuid:candidate_id>/adopt/",
        adoption_views.candidate_adopt,
        name="candidate_adopt",
    ),
    path(
        "analyses/<uuid:analysis_id>/candidates/<uuid:candidate_id>/reject/",
        adoption_views.candidate_reject,
        name="candidate_reject",
    ),
    path(
        "<uuid:session_id>/discard/",
        views.capture_discard,
        name="capture_discard",
    ),
    path(
        "analyses/<uuid:analysis_id>/structured-review/",
        structured_views.structured_review,
        name="structured_review",
    ),
    path(
        "analyses/<uuid:analysis_id>/structured-review/<uuid:batch_id>/items/<uuid:item_id>/decide/",
        structured_views.structured_review_decide,
        name="structured_review_decide",
    ),
    path(
        "analyses/<uuid:analysis_id>/structured-review/<uuid:batch_id>/commit/",
        structured_views.structured_review_commit,
        name="structured_review_commit",
    ),
    path(
        "processes/<uuid:process_pk>/solution-generation/start/",
        solution_generation_views.solution_generation_start,
        name="solution_generation_start",
    ),
    path(
        "solution-generations/<uuid:run_id>/preview/",
        solution_generation_views.solution_generation_preview,
        name="solution_generation_preview",
    ),
    path(
        "solution-generations/<uuid:run_id>/repair/",
        solution_generation_views.solution_generation_repair,
        name="solution_generation_repair",
    ),
    path(
        "solution-generations/<uuid:run_id>/adopt/",
        solution_generation_views.solution_generation_adopt,
        name="solution_generation_adopt",
    ),
]
