# Generated by Django 5.2.16 on 2026-09-29 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0006_alter_historicalgovernanceassessment_rationale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='governanceassessment',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='governancereview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_governance_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
