# Generated by Django 5.2.16 on 2026-09-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0007_alter_governanceassessment_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governanceassessment',
            name='automated_person_assessment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='governanceassessment',
            name='biometric_data',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='governanceassessment',
            name='employee_data',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='governanceassessment',
            name='external_ai_or_cloud',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='governanceassessment',
            name='generated_external_content',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='governanceassessment',
            name='health_safety_rights_impact',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='governanceassessment',
            name='human_oversight_planned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='governanceassessment',
            name='influences_person_decisions',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='governanceassessment',
            name='personal_data',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='governanceassessment',
            name='regulated_product',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='governanceassessment',
            name='safety_critical',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgovernanceassessment',
            name='automated_person_assessment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgovernanceassessment',
            name='biometric_data',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgovernanceassessment',
            name='employee_data',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgovernanceassessment',
            name='external_ai_or_cloud',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgovernanceassessment',
            name='generated_external_content',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgovernanceassessment',
            name='health_safety_rights_impact',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgovernanceassessment',
            name='human_oversight_planned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgovernanceassessment',
            name='influences_person_decisions',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgovernanceassessment',
            name='personal_data',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgovernanceassessment',
            name='regulated_product',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgovernanceassessment',
            name='safety_critical',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
