# Generated by Django 5.2.16 for VS1/1

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accelerator", "0010_solution_quality_run"),
        ("architecture", "0020_solutionoption_work_design_origin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestigationSourceFolder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("root_path", models.TextField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "process_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investigation_source_folders",
                        to="architecture.processanalysis",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_investigation_source_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["process_analysis_id", "name"]},
        ),
        migrations.AddConstraint(
            model_name="investigationsourcefolder",
            constraint=models.UniqueConstraint(
                fields=("process_analysis", "root_path"),
                name="uniq_investigation_folder_process_path",
            ),
        ),
        migrations.CreateModel(
            name="InvestigationSourceSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("process_version", models.PositiveIntegerField()),
                ("decision_question", models.TextField()),
                ("run_limits", models.JSONField(default=dict)),
                ("process_context", models.JSONField(default=dict)),
                ("manifest_hash", models.CharField(max_length=64)),
                (
                    "captured_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_investigation_source_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="accelerator.investigationsourcefolder",
                    ),
                ),
                (
                    "process_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investigation_source_snapshots",
                        to="architecture.processanalysis",
                    ),
                ),
            ],
            options={"ordering": ["process_analysis_id", "-revision"]},
        ),
        migrations.AddConstraint(
            model_name="investigationsourcesnapshot",
            constraint=models.UniqueConstraint(
                fields=("folder", "revision"),
                name="uniq_investigation_folder_revision",
            ),
        ),
        migrations.CreateModel(
            name="InvestigationSource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("txt", "TXT"), ("md", "Markdown"), ("csv", "CSV")],
                        max_length=10,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("size_bytes", models.PositiveIntegerField()),
                ("content_sha256", models.CharField(db_index=True, max_length=64)),
                ("captured_mtime", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField()),
                ("row_count", models.PositiveIntegerField(blank=True, null=True)),
                ("column_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("columns", models.JSONField(blank=True, default=list)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duplicate_sources",
                        to="accelerator.investigationsource",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="accelerator.investigationsourcesnapshot",
                    ),
                ),
            ],
            options={"ordering": ["filename", "id"]},
        ),
        migrations.AddConstraint(
            model_name="investigationsource",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "filename"),
                name="uniq_investigation_snapshot_filename",
            ),
        ),
        migrations.CreateModel(
            name="InvestigationToolResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        choices=[
                            ("profile_csv", "CSV profilieren"),
                            ("compare_groups", "Gruppen vergleichen"),
                        ],
                        max_length=30,
                    ),
                ),
                ("tool_version", models.CharField(max_length=30)),
                ("source_hash", models.CharField(max_length=64)),
                ("parameters", models.JSONField(default=dict)),
                ("result_payload", models.JSONField(default=dict)),
                ("population", models.JSONField(default=dict)),
                ("excluded_rows", models.JSONField(default=list)),
                ("group_sizes", models.JSONField(default=dict)),
                ("missing_values", models.JSONField(default=dict)),
                ("units", models.JSONField(default=dict)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investigation_tool_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_results",
                        to="accelerator.investigationsourcesnapshot",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_results",
                        to="accelerator.investigationsource",
                    ),
                ),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AddIndex(
            model_name="investigationtoolresult",
            index=models.Index(
                fields=["snapshot", "tool_name", "created_at"],
                name="invtool_snapshot_tool_idx",
            ),
        ),
    ]
