# Generated by Django 5.2.16 on 2026-09-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0013_decision_brief_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationmodelcall',
            name='role',
            field=models.CharField(choices=[('planner', 'Planner'), ('synthesizer', 'Synthesizer'), ('verifier', 'Verifier')], max_length=20),
        ),
    ]
