# Generated by Django 5.2.16 on 2026-09-27 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0015_scope_active_investigation_runs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationrun',
            name='execution_generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='execution_lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='execution_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='execution_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_investigation_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='execution_worker_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationstep',
            name='attempt_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
