# Generated by Django 5.2.16 on 2026-09-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("architecture", "0020_solutionoption_work_design_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="solutionarchitectureassessment",
            name="ap2_provenance",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
