# Generated by Django 5.2.16 on 2026-09-29 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0021_solutionarchitectureassessment_ap2_provenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionarchitectureassessment',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_architecture_assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
